### ISSUE TITLE
Submitting a proposal on my DAO

### ISSUE THREAD

**Issue by IamAlnoor** [near-daos/astro-ui#1002]
I am unable to process any proposals and keep getting an error code. Please see attached image to show the error message.
 Thank you,
 Alnoor
 
 [](url
![NEAR Error](https://user-images.githubusercontent.com/104385434/165198418-a1186824-19a9-400a-8c0f-c2229508ca3d.jpg)
)

**Comment by VERZUOL1** [comment]
Hi, 
can you please share a link to DAO you create proposal in and a type of proposal you try to create?

Thanks!

**Comment by IamAlnoor** [comment]
Hi,
Thank you for looking into my ticket - please see the screenshots below.
These transactions have also incurred TGAS fees.- can these be reimbursed?
Thank you,
Alnoor

[image: photo]
*Alnoor Damji*
VP International Events

Krisullis
<https://streaklinks.com/BCSqTj76-jVfrLkknwdLvCtC/http%3A%2F%2Fkrisullis.com%2F>
<https://streaklinks.com/BCSqTj7KCuL66R-JfwLgJS_K/http%3A%2F%2Fca.linkedin.com%2Fin%2Falnoordamji>
<https://streaklinks.com/BCSqTj7TU2DrLhn7tQIQSkRQ/http%3A%2F%2Fwww.youtube.com%2Fchannel%2FUCIO3Aim7ig1PlCkieomxeFQ>
<https://streaklinks.com/BCSqTkchIR0Ri-W6qAIb8Dd5/http%3A%2F%2Ffacebook.com%2FIamAlnoor>
<https://streaklinks.com/BCSqTj7BQYIlx7lQYA_dMKRW/http%3A%2F%2Finstagram.com%2FIamAlnoor>
<https://streaklinks.com/BCSqTkQj47DZs6NFBQ5VUKuU/http%3A%2F%2Ftwitter.com%2FIamAlnoorYYC>

ᐧ

**Comment by dmytro-almighty** [comment]
dont have enough information to reproduce, please try to adjust gas amount in the proposal UI
