### ISSUE TITLE
Can't vote on the DAO to upgrade binary version

### ISSUE THREAD

**Issue by GaloisField2718** [near-daos/astro-ui#1009]
**Describe the bug**
When I want to approve the binary upgrade of the DAO I have : {"index":0,"kind":{"ExecutionError":"Exceeded the account balance."}}

**To Reproduce**

1. Go to 'https://testnet.app.astrodao.com/dao/anank.sputnikv2.testnet/governance/settings/version'
2. Click on 'Approve'
3. Click on 'Approve' in pop-up wallet's window 
4. See error : {"index":0,"kind":{"ExecutionError":"Exceeded the account balance."}}

**Expected behavior**

**Screenshots**
<img width="1260" alt="Capture d’écran 2022-04-27 à 17 11 50" src="https://user-images.githubusercontent.com/84255448/165551267-d3cc5852-0505-407a-b9f1-7ae5d5a728eb.png">

**Desktop :**

- OS: [e.g. iOS] : Mac OS Monterrey
- Browser [e.g. chrome, safari] : Brave
- Version [e.g. 22]: [Version 1.36.112 Chromium: 99.0.4844.51 (Build officiel) (x86_64)](https://brave.com/latest/)

**Comment by GaloisField2718** [comment]
When I vote with each account it's working but I can't approved the proposal because the half of account can't vote. 
Do you have any ideas of what can I do ?

**Comment by VERZUOL1** [comment]
Hi @GaloisField2718,
this feature is still in development. Actually you can perform all the steps in the wizard on test envireonment but nothing will be changed on your DAO.
Regarding the error you got - as far as I rememeber it requires at least 6 NEAR to be on DAO balance to peform the upgrade.
Also, please dont change attached Gas on proposal - default values must work as expected.

**Comment by GaloisField2718** [comment]
Hi, 

I try to add 10 NEAR in the DAO by 
But I have the same error : {"index":0,"kind":{"ExecutionError":"Exceeded the account balance. »}}
I don’t know how to solve. 

I will try to use « Fund ».

**Comment by dmytro-almighty** [comment]
workign version deployed on testnet and prod
