### ISSUE TITLE
Add one word labels below the icons for easier navigation

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#102]
Issue 8 https://github.com/near-daos/astro-ui/issues/91

Put them in this order:

- “Proposals” (currently no icon for this)
- “Treasury” under the coins icon.
- “NFTs” under the easel.
- “Members” under people icon.
- “Settings” under gear icon
- Remove (these can be navigated to via the “Proposals” page):
> - “Bounties”
> - “Polls” 

![image](https://user-images.githubusercontent.com/94607182/144020731-09cb7620-201c-4350-9306-a3228bb4fc7c.png)

**Comment by dmytro-almighty** [comment]
will play with the design to see if it will work.
regarding removing bounties/polls - you indeed can access proposals to create/finish bounty from the proposals page, but it's not the same with the bounty/polls entities.
