### ISSUE TITLE
Remove elements

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#103]
Issue 9 https://github.com/near-daos/astro-ui/issues/91

- Remove filter on proposals detail page.
- Hovering over the Proposal card on this page makes the cursor a pointer but clicking on the card doesn’t do anything. Only make the cursor a pointer when it’s above something to click on.

![image](https://user-images.githubusercontent.com/94607182/144021191-d9f5e399-aadb-4ff8-9ce9-d45ce334c652.png)

**Comment by dmytro-almighty** [comment]
We can remove the filter, but what is the logic behind it? It's suitable for users to have the possibility to filter out votes and align with the rest of the pages.
Regarding the hover effect on the card - it exists only on the explorer button.
