### ISSUE TITLE
Could not finish creating my wallet account

### ISSUE THREAD

**Issue by hoanaolho** [near-daos/astro-ui#1041]
My wallet account doesn't seem to exist.
I just can not access and when I try to recover (by the link I got by email), it says "We found 0 accounts secured by this link" as the screenshot:

![image](https://user-images.githubusercontent.com/105012505/166986968-997ebd50-961e-4b24-bc8f-804155de4ba1.png)

I think I had a problem when I was finisthing to create my wallet and now I am stucked.

Is that a way to finish creating my wallet? 

Thank you very much

Hoana

**Comment by dmytro-almighty** [comment]
its not relevant to Astro UI, you should post your question in Wallet repo
