### ISSUE TITLE
Rework DAO page

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#105]
Issue 11 https://github.com/near-daos/astro-ui/issues/91

- Display the “DaoDetailsMin Nav Bar” on the DAO detail page.
- Rearrange the other cards on DAO detail page 
- Remove card of icons since they already appear in the “DaoDetailsMin Nav Bar” 
- Add “Copy DAO Address” icon to the “DaoDetailsMin Nav Bar” (this addition should be visible on every page where users see the “DaoDetailsMin Nav Bar”)

![image](https://user-images.githubusercontent.com/94607182/144021693-c64520f0-5149-439d-93a1-185f6680c63e.png)

**Comment by dmytro-almighty** [comment]
The minimized DAO header is helpful to provide DAO context for the user, but it cannot replace the main header of the DAO page. All widgets on the main DAO page is designed with a single purpose, to provide an overview of DAO stats (including DAO flag) to the end-user.
After the drill down to the specific page, we render the minimized DAO page to keep user connection with the rest of the DAO, focusing more on DAO page content.
No plans to implement this.

**Comment by starpause** [comment]
Consistent navigation between all pages of the DAO is required. Even if we have to duplicate the slim DAO header in addition to the full DAO header it's better than not having the slim DAO header on every view of the DAO page.
