### ISSUE TITLE
Adding proposal shows extra 0.1 N charge in wallet transaction

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#1052]
**Describe the bug**
AstroDAO is charging 0.2 NEAR when bond is 0.1 NEAR

<img width="612" alt="image" src="https://user-images.githubusercontent.com/408953/167501860-66964557-4497-44ad-b360-50ebc6611067.png">

![image](https://user-images.githubusercontent.com/408953/167501805-695e01ef-cac0-4a2c-af36-7f19464a6e1b.png)

I looks like the extra 0.1N is being used as a storage deposit to register an account. Since it's returned there isn't a financial issue, but it's confusing for the user to see 0.2 N deposit on the transaction after the AstroDAO UI showed that only a 0.1 N deposit is required. Example of the storage deposit being returned:

https://explorer.near.org/transactions/974ro2gaSRt2ZiaKxXwqhp7fhvDg8V4D8WXsFagHXyv5
https://nearblocks.io/txns/974ro2gaSRt2ZiaKxXwqhp7fhvDg8V4D8WXsFagHXyv5#execution

**Comment by VERZUOL1** [comment]
Added an info with tooltip if we create transfer or create bounty proposal using FT so we have to create storage.
