### ISSUE TITLE
Visually align items on a global grid

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#106]
Issue 12 https://github.com/near-daos/astro-ui/issues/91

When no grid is followed the page looks janky and difficult to scan. 

![image](https://user-images.githubusercontent.com/94607182/144021873-55cb9ddd-a981-4f75-87eb-1f580ef60f3c.png)

**Comment by dmytro-almighty** [comment]
We will align the search bar with the rest of the elements. The text within elements should not be aligned since all UI elements have a completely different context.

**Comment by starpause** [comment]
<img width="1555" alt="image" src="https://user-images.githubusercontent.com/408953/144697021-2e67ae03-208f-4fef-879f-60260fa48d62.png">

Please bring the header into alignment with the page content.

Overall, the context doesn't matter. If there is not a global grid the page layout looks sloppy. Subconsciously it's distracting (like a cluttered room) and prevents users from being able to quickly scan content.

**Comment by starpause** [comment]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/408953/144699508-cd127d3d-d7bf-40aa-85ba-3aa028a52b67.png">

Another example where elements are lacking alignment. Left justify Breadcrumbs, cards, and proposal filter to the red line.

The flag is much too big and blurry (circled in green). Decrease it's size so it fits inside the card (pink box).
