### ISSUE TITLE
Notification labeled as "Your's" when I didn't create the proposal.

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#1070]
**Describe the bug**

![image](https://user-images.githubusercontent.com/408953/168121237-759ecb97-cd73-47f7-94db-f5731bf54b25.png)

Regarding

https://app.astrodao.com/dao/deitydao.sputnik-dao.near/proposals/deitydao.sputnik-dao.near-10

My vote did pass the proposal, but I didn't create the proposal. The proposer is monkegodznft.near

You can see that when Kingbanana voted the notification also has Kingbanana as the creator of the proposal.

It's also frusterating that I can't highlight text on the card and copy it. I would suggest replacing the text "kingbanana's Function call proposal in the DeityDAO DAO" with "function call proposal #10 by kingbanana in DeityDAO" and make that text clickable to go see the details of the function call. 

https://user-images.githubusercontent.com/408953/168122552-10ec4401-a5b6-4edc-b24b-c7d300dd52ae.mp4

**Comment by VERZUOL1** [comment]
Fixed wrong labels.
Notification is clickable and user navigated to proposal page.
