### ISSUE TITLE
Connecting to the Wallet takes ages?!

### ISSUE THREAD

**Issue by 1DRRX** [near-daos/astro-ui#1077]
Hi there.

Hope u guys are doin gr8!

It looks like Connecting to the Wallet is taking Never Ending time!

Please instruct.

Many thanks in advance.

Regards,
Dr. SM Mizanul
drsms@1dxn.com

![Screenshot 2022-05-16 030345](https://user-images.githubusercontent.com/101579254/168493925-7feb67eb-68bc-429c-8b6d-6b6bfe22556b.jpg)

**Comment by dmytro-almighty** [comment]
@1DRRX  can you please try to clean the cookies and localstorage and perform login one more time?
