### ISSUE TITLE
{"index":0,"kind":{"ExecutionError":"Exceeded the prepaid gas."}}

### ISSUE THREAD

**Issue by jdlebrija** [near-daos/astro-ui#1107]
![Error Prepaid](https://user-images.githubusercontent.com/106277490/170357624-278367cc-c882-4cff-b6c5-92354db65107.jpg)

**Comment by VERZUOL1** [comment]
Hi,
can you please provide more details about an action caused this error? Or transaction link to explorer

**Comment by jdlebrija** [comment]
I was trying to migrate in AstroDAO from V2 to V3

**Comment by dmytro-almighty** [comment]
the upgrade is no longer available due to the gas calculation changes on the mainnet, the only way to migrate is to create new v3 dao and migrate all the funds
