### ISSUE TITLE
Closed proposal which appears to be open in Astro ui

### ISSUE THREAD

**Issue by GaloisField2718** [near-daos/astro-ui#1113]
**Describe the bug**
When I'm using near-cli, I see the proposal as Closed :
```bash
View call: anank.sputnikv2.testnet.get_proposal({"id":11})
{
  id: 11,
  proposer: 'anank2.testnet',
  description: 'Are you agree whit the fact that DAO is unuseful ?$$$$$$$$ProposePoll',
  kind: 'Vote',
  status: 'Approved',
  vote_counts: { council: [ 1, 0, 0 ], 'Active member': [ 2, 1, 0 ] },
  votes: {
    'anank1.testnet': 'Approve',
    'anank2.testnet': 'Reject',
    'anank3.testnet': 'Approve'
  },
  submission_time: '1653899993127723508'
}
```
When I'm looking on astro ui : 
<img width="954" alt="Capture d’écran 2022-05-30 à 11 19 18" src="https://user-images.githubusercontent.com/84255448/170960785-c5912eff-8146-4ea8-8af0-1301c6bcbaa5.png">

How to update Astro printing ? 

I'm using Brave ([Version 1.38.111 Chromium: 101.0.4951.54 (Build officiel) (x86_64)]) if it's useful.

**Comment by VERZUOL1** [comment]
It is already fixed, looks like a delay in updating db.
![image](https://user-images.githubusercontent.com/40799684/171846611-3d52df51-8c79-4bc5-a538-347cce220ff0.png)

**Comment by GaloisField2718** [comment]
Okay thanks
