### ISSUE TITLE
No permissions to vote or add proposals

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-daos/astro-ui#1166]
**Describe the bug**
We have a DAO with 1 group: `council`. In this group, anyone can do everything so we set permissions in the policy to `*:*`.
The smart contract is fine, as we're able to vote from cli, but AstroDAO doesn't display buttons to create or vote on proposals. Seems like it's interpreting the permissions incorrectly.

**To Reproduce**

1. Create a DAO with one group: council.
2. Set permissions to `*:*`
3. Open the DAO on Astro UI, see no buttons to vote or add proposals

**Expected behavior**
Buttons to add or vote on proposals.

**Screenshots**
<img width="751" alt="image" src="https://user-images.githubusercontent.com/28174037/173051733-33b0f502-2110-4f2b-9727-5175d9e3da6b.png">

**Desktop (please complete the following information):**

- OS: windows 11
- Browser: firefox, brave
- Version: latest

**Additional context**
We created the DAO using cli, but I think we still should be able to vote from Astro UI if the smart contract permissions allow us to.

**Comment by VERZUOL1** [comment]
Hello!

Here is a roles object from your DAO:

"roles": [
      {
        "createdAt": "2022-06-10T10:10:19.443Z",
        "id": "test-multicall.sputnik-dao.near-council",
        "name": "council",
        "kind": "Group",
        "balance": null,
        "accountIds": [
          "multicall.near",
          "lennczar.near",
          "sooyaaa.near"
        ],
        "permissions": [
          "*:*"
        ],
        "votePolicy": {}
      }
    ]

It means that in **test-multicall.sputnik-dao.near** there is a group named **council** and member of this group have all the permissions in the application. 
This setup doesn't allow anyone who is not a council in DAO to create proposals or vote.
There should be a role with **kind: 'Everyone'** to allow other users to create proposals.
Here is a working example:
{
        "createdAt": "2022-02-02T14:23:11.914Z",
        "id": "pets.sputnikv2.testnet-all",
        "name": "all",
        "kind": "Everyone",
        "balance": null,
        "accountIds": null,
        "permissions": [
          "*:AddProposal"
        ],
        "votePolicy": {}
      }

**Comment by VERZUOL1** [comment]
With current permissions setup only councils can create proposals.
