### ISSUE TITLE
Locked Funds

### ISSUE THREAD

**Issue by IgbozeIsrael** [near-daos/astro-ui#1170]
Hello!
We have funding from Marketing DSO for our guild's activities but funds are locked. What is the problem and how do we get it unlocked?
9jamusicalnftdao.sputnik-dao.near is our DAO name.

**Comment by VERZUOL1** [comment]
Hi,
the funds are not locked, your funds are avaialble in DAO 
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/40799684/173542250-28e7dae2-d831-4553-8564-1835e9b85209.png">
