### ISSUE TITLE
Function call proposals only display the first action

### ISSUE THREAD

**Issue by mohamedalichelbi** [near-daos/astro-ui#1436]
**Describe the bug**
The [SputnikDAO contract](https://github.com/near-daos/sputnik-dao-contract/blob/640495ba572345ca356376989738fbd5462e1ff8/sputnikdao2/src/proposals.rs#L329) allows executing multiple actions (a batch) in a FunctionCall proposal. However, the UI assumes that there's always one action only, which can be misleading when DAO members are reviewing a proposal to vote on it.
As an example: looking at the UI, one might think that [this proposal](https://testnet.app.astrodao.com/dao/akaia.sputnikv2.testnet/proposals/akaia.sputnikv2.testnet-18) only pays storage on some token contract. But looking at the proposal creation [TX on explorer](https://explorer.testnet.near.org/transactions/3t5WGpEyopiX1yKHPG5V6KyTX4azGqXtdyi4E1YMmSY7) one can tell that the proposal executes `ft_transfer_call` as well.

**To Reproduce**

1. Use cli (or a script) to create a FunctionCall proposal that has multiple actions (like calling `ft_transfer` twice).
2. Open AstroUI to visualize that proposal
3. See how only the first action is displayed. No indication that there are other actions as well

**Expected behavior**
Either display the list of all actions, or give some indication that there are multiple actions.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
This can be used maliciously to mislead DAOs by making an innocent-looking first action, like a token transfer by an agreed-upon amount, followed by a second action that transfers more of the token out of the DAO's balance.

**Comment by dmytro-almighty** [comment]
fixed on mainnet
