### ISSUE TITLE
Bug: Implicit Account Address UI Can't Action

### ISSUE THREAD

**Issue by agileurbanite** [near-daos/astro-ui#1452]
**Describe the bug**
![telegram-cloud-photo-size-2-5242625394794938415-y](https://user-images.githubusercontent.com/2501324/188963060-7e2ea8ed-215e-4c7b-aea4-54256a8d4292.jpg)

Implicit account address can't action because of overlap with buttons

**Comment by VERZUOL1** [comment]
Already fixed
