### ISSUE TITLE
Some of categories of group do not show members

### ISSUE THREAD

**Issue by hsxyl** [near-daos/astro-ui#1480]
**Describe the bug**
Some of categories of group do not show members.

**To Reproduce**

1. Go to https://testnet.app.astrodao.com/dao/octopus-dao.sputnikv2.testnet/groups/council-manager
2. See error.

**Expected behavior**
Should show account(octopus-council.registry.test_oct.testnet) in this page.

**Screenshots**
![image](https://user-images.githubusercontent.com/20741814/191885017-1cbe21f1-5eff-4ff4-a116-26140b5afc3c.png)

![image](https://user-images.githubusercontent.com/20741814/191885066-d455a4f1-4877-407d-919d-23ce4515a632.png)

**Comment by dmytro-almighty** [comment]
fixed on mainnet
