### ISSUE TITLE
NFT cards on "NFTs" page are trimming the original image

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#176]
Related to #10

---
![image](https://user-images.githubusercontent.com/94607182/145168095-97de3c9c-39fc-44be-819f-26bc494ab9d1.png)

![image](https://user-images.githubusercontent.com/94607182/145168250-13662dab-6004-40e9-a892-e7d5ab0ea194.png)

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed

**Comment by Izek** [comment]
Verified in testnet app. Ready for Stage
