### ISSUE TITLE
[Bounties] Implement filtering of bounties by statuses the same way as proposals

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#190]
Env: Dev

Implement Filter by status radio group for bounties the same way as it implemented for proposals:
* Available
* Claims in Progress
* Expired Claims

<img width="1450" alt="Screenshot 2021-12-09 at 20 17 04" src="https://user-images.githubusercontent.com/4663708/145453859-8a59ab48-29a3-40e2-a636-3fcc1adea552.png">
<img width="1498" alt="Screenshot 2021-12-09 at 20 17 22" src="https://user-images.githubusercontent.com/4663708/145453867-7253ede5-de92-4420-9dad-1d2c951c23da.png">

**Comment by dmytro-almighty** [comment]
@Izek close this one, the page will be redesigned from the scratch
