### ISSUE TITLE
[Bounties] Display Bounty reward in "Bounty Done" proposal card

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#191]
Display reward amount in "Bounty Done" proposals the same way its displayed for Bounty proposal
<img width="940" alt="Screenshot 2021-12-09 at 20 28 59" src="https://user-images.githubusercontent.com/4663708/145454805-1b4f3217-5057-4a79-9069-9e4707649dec.png">

**Comment by VERZUOL1** [comment]
These details are not available in bounty done proposal kind. We have no way to show it.
