### ISSUE TITLE
bounty flow ux improvements

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#197]
When claiming a bounty, there is no warning that on chain activities take a while to appear. There was no visual indicator that I'd successfully claimed the bounty. I was confused and claimed it several times. This is the kind of message I expected to see if the results are not immediate: 

![image](https://user-images.githubusercontent.com/408953/145764821-1c29d4a7-af3e-4d9d-94f5-3e21d4b8d604.png)

Small inconstancy: green icon rather than purple:

![image](https://user-images.githubusercontent.com/408953/145765187-87fa42d8-22f4-4dbb-bce6-0cd70f7c3b45.png)

Add "Due on" in front of the date for InProgress bounties:

![image](https://user-images.githubusercontent.com/408953/145765472-73d04cb9-f530-4026-b1a0-4f981ff879d3.png)

Remove the loading spinners. It makes it look like there is content loading that hasn't populated yet, which is confusing. It's also distracting on an already busy page.

![image](https://user-images.githubusercontent.com/408953/145765790-d7e8fc2f-29f4-4158-9b3d-778b794fbe12.png)

After "Complete" redirect user to the page they were just on () rather than the proposal page (). Add a link to the proposal(s) that have been made to complete the work with a label like "Completion Proposals"

![image](https://user-images.githubusercontent.com/408953/145767129-a437c702-f7fe-4c33-95a7-910ff65bdecd.png)

Add numbers for "in progress claims" and "completed claims"

![image](https://user-images.githubusercontent.com/408953/145768685-723567c3-0507-407e-a8ee-937e745c5cdb.png)

**Comment by wnwd-oleksii-p** [comment]
We should add functionality that single account can not claim bounty more than once.

**Comment by AlexeyPonomarenko** [comment]
Also user shouldn't be able to claim a single bounty twice.
