### ISSUE TITLE
Add warning that browser setting "Pop-ups and redirects" should be enabled for a new Payout proposals

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#208]
If the browser setting "Pop-ups and redirects" is disabled - the new proposal is not showing up in a DAO.

---
![image](https://user-images.githubusercontent.com/94607182/146176813-95d3399a-bbd1-4799-b450-6a51672ffe94.png)

**Comment by VERZUOL1** [comment]
fixed in dev
