### ISSUE TITLE
Change the meta description of AstroDAO

### ISSUE THREAD

**Issue by cuongdcdev** [near-daos/astro-ui#220]
We need to change the meta description of astrodao.com, currently, it shows the default description from create-react-app tool.
![Screenshot_22](https://user-images.githubusercontent.com/12132077/146596813-7695dd01-7a4e-4eeb-b91d-7212bd614f1c.png)

**Comment by Izek** [comment]
Can be verified only after deployment to https://astrodao.com/

Moving to Ready for Prod
