### ISSUE TITLE
AstroDAO is not compatible with 2FA

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#228]
Getting gas limit exceeded error.

**Comment by starpause** [comment]
_Via VG:_

I think I know the source of issue

https://explorer.near.org/transactions/3atxf8WEVQd9AUq3X8esheQ1bSdfPbvpABGn3qng9qMN

looks like Astro UI attaches 250 Tgas for the add_proposal call

but wallet also gives 250 Tgas for whole 2FA call, so there is no space

it is also definitely an overkill, e.g. here  250 Tgas attached 7 Tgas used:
https://explorer.near.org/transactions/2KhQFAETK39NzFpsFyH2UdZz4934FHfNWkPhd4vA1nzj

**Comment by starpause** [comment]
![image](https://user-images.githubusercontent.com/408953/147668769-fbe5cd12-1f0c-4e2d-bb48-e4096a21e9c4.png)

Is confusing because gas is not measured in NEAR. Instead, measure in Tgas (same as it shows in explorer).

Also confusing that it's not obviously a text box which can be edited. 

Default value should be low (100 Tgas).

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed. Now TGas default value is 0.1

**Comment by RomaSha2010** [comment]
Verified on testnet. Fixed
