### ISSUE TITLE
[Filter by status][Feed] Didn't work when change a filter at first time

### ISSUE THREAD

**Issue by IlliaMiM** [near-daos/astro-ui#246]
**Step to reproduce:**
- Open Feed page
- Click on the "All" OR else status type  

Missing a parameter (example https://dev.app.astrodao.com/api-server/v1/proposals + parameter)
Fixed on repeated filter change or page refresh.

**Expected results** 
Showed only Active proposals. After replacing the filter, the proposals list also changes

**Actual results**
Nothing.

**Comment by VERZUOL1** [comment]
Fixed in latest build
