### ISSUE TITLE
[MOBILE] Search results with long names lead to scrollbar appearance and card offset

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#291]
Tested on Pixel 5. Android 12

**STR:**
- Enter "testdao3" in a Search field

**ER:**
- Search results with long names are fit to screen
- Cards are not offset

**AR:**
- Search results with long names are not fit to screen
- Cards are offset

---
![image](https://user-images.githubusercontent.com/94607182/147414698-209343c6-9f3c-4784-b0a8-cf0645a9ad40.png)
![image](https://user-images.githubusercontent.com/94607182/147414699-21d9023b-f2aa-43ca-99fe-67a092a87029.png)

**Comment by AlexeyPonomarenko** [comment]
Design team will provide update and we'll implement it. Please, ping Alena for clarifications/updates according design.

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed

**Comment by RomaSha2010** [comment]
Verified on testnet. Fixed
