### ISSUE TITLE
[Global Feed] Display filter name instead of button

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#298]
AR: Filter button is displayed with no indication of what filter is enabled at the moment.
ER: There should be displayed what filter is enabled at the moment.

![Screenshot 2021-12-26 at 21 30 36](https://user-images.githubusercontent.com/4663708/147418232-5f3032be-2d5d-4ca3-bd9c-5601564d1d01.png)
![Screenshot 2021-12-26 at 21 30 48](https://user-images.githubusercontent.com/4663708/147418234-346496b5-6ddb-4e96-b927-9ae3e4fa4be8.png)

**Comment by AlexeyPonomarenko** [comment]
Mock:
https://www.figma.com/file/ifhZLG9EP01RFmj4UnWtLv/Astro---MP-v.2?node-id=7695%3A55839
