### ISSUE TITLE
[Mobile] [All Communities] Too much space between items in mobile view + duplicated button "Create DAO"

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#299]
1) AR: Too much space between top bar and "All communities" label.
    ER: "All communities" label should be placed higher.

2) AR: "Create new DAO" button at the top of the screen duplicates "Create DAO" button in the bottom tab bar in mobile view.
     ER: "Create new DAO" button should not be displayed in mobile view

![Screenshot 2021-12-26 at 21 35 53](https://user-images.githubusercontent.com/4663708/147418427-b342e9fe-9de1-4d0a-8ce2-5da2d6cfc9dd.png)

**Comment by wnwd-oleksii-p** [comment]
Discussed with the design team. UI looks as expected and should remain the same.

**Comment by AlexeyPonomarenko** [comment]
Discussed with design team. UI looks as expected and should not be changed.
