### ISSUE TITLE
proposal description

### ISSUE THREAD

**Issue by sainthiago** [near-daos/astro-ui#3]
hello everyone,

when I try to create a proposal, as soon as it appears in astro dao, the proposal description on the screen doesn't match the one I put in the object, although it comes in the endpoint that brings the proposal information. 

note: the code that i wrote worked on sputnikv2.

![photo1636412416](https://user-images.githubusercontent.com/11164548/140849626-0294f9db-8f6f-4c49-8252-73e1c52ec1a7.jpeg)

if you need any extra info let me know,
thanks

**Comment by VERZUOL1** [comment]
Fixed.
Should be available on testnet this evening.
