### ISSUE TITLE
[NFTs] Preview content of Image and GIF NFTs is displayed incorrectily

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#315]
AR: Image and GIF NFTs are trimmed from the edges.
ER:  Image and GIF NFTs should be fully fitted into the card edges.
![Screenshot 2021-12-27 at 17 08 06](https://user-images.githubusercontent.com/4663708/147484230-9b34fbd2-cab1-43be-a038-9e7608b9dd39.png)
![Screenshot 2021-12-27 at 17 07 36](https://user-images.githubusercontent.com/4663708/147484235-f08ff18b-89a5-4736-8f0c-2385655041ec.png)

**Comment by Izek** [comment]
https://www.figma.com/file/ifhZLG9EP01RFmj4UnWtLv/Astro---MP-v.2?node-id=8349%3A57100
Design

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed

**Comment by Izek** [comment]
Verified in testnet app. Ready for Stage
