### ISSUE TITLE
[DAO] Make default setting  "All"  for  DAO Funds graph in DAO page

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#321]
![2021-12-28 20 59 59](https://user-images.githubusercontent.com/4663708/147598420-9537dba6-3d5b-4530-a0c9-5d1d391b2045.jpg)

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed

**Comment by Izek** [comment]
Verified in testnet app. Ready for Stage
