### ISSUE TITLE
Add Fields to capture DAO Legal Status

### ISSUE THREAD

**Issue by ankitbuti** [near-daos/astro-ui#34]
We need 2 new fields:

1.  Type: Free Text, Name: "Legal Status", Description Placeholder: "Please explain your DAO's Legal Status and Jurisdiction (if known)"
2. Type: URL, Name: "Attached Legal Doc", Description: "Please attach a link to the relevant PDF / Document as proof of legal status"

They are **NOT Mandatory**.

These should be available in both 1. DAO Creation Interface & 2. DAO Settings Page.

This data doesn't have to be stored in on-chain smart contract, this can live in the middleware Postgres db as DAO meta-data.

**Comment by ilblackdragon** [comment]
DAO has a metadata field on-chain where data like this can and IMO should live.
