### ISSUE TITLE
Skinny proposal rendering on page load

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#357]
At URL https://app.astrodao.com/my/feed I have gotten this odd rendering several times. If I resize my browser window the rendering is fine. It doesn't happen every time I visit the page so I don't have steps to consistently reproduce.

![image](https://user-images.githubusercontent.com/408953/147936495-a23e8aee-1913-41e1-b277-3b069857623f.png)

**Comment by RomaSha2010** [comment]
Not actual anymore
