### ISSUE TITLE
Functional call proposal for token creation via DAO is failed, due to too much GAS being attached, displayed as Approved on UI

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#386]
[Proposal URL](https://dev.app.astrodao.com/dao/bounty-test-release-3-0.sputnikv2.testnet/proposals/bounty-test-release-3-0.sputnikv2.testnet-5)

Functional call for token creation via DAO is failed due to too much GAS being attached

[Succeeded transaction for FC](https://explorer.testnet.near.org/transactions/CYQgtuinsDZHEBZJfx4wQgnV6oNoytqx2vFDiezdiwQT)
[Failed Vote transaction](https://explorer.testnet.near.org/transactions/AVpeDPXVYomUMrGT41mkvaBvwi2JynpCcbvJGYKWBPvv)
`{
  "ActionError": {
    "index": 0,
    "kind": {
      "FunctionCallError": {
        "ExecutionError": "Exceeded the prepaid gas."
      }
    }
  }
}`

**Comment by dmytro-almighty** [comment]
already fixed
