### ISSUE TITLE
Add this Repo as a link in sidebar

### ISSUE THREAD

**Issue by TrevorJTClarke** [near-daos/astro-ui#4]
<img width="280" alt="Screen Shot 2021-11-09 at 8 10 32 AM" src="https://user-images.githubusercontent.com/2633184/140961197-b000cb5d-6fc5-4388-8021-c9fce9db35a4.png">

Currently there's no way to know this repo exists from the UI

**Comment by VERZUOL1** [comment]
Fixed.
Should be available on testnet this evening.
