### ISSUE TITLE
[Proposals] Change "Not Voted" icon in the list of voters

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#400]
AR: "Not Voted" icon looks like context menu button for mobile users, which may confuse people
ER: "Not Voted" icon should reflect its state 

![Screenshot 2022-01-11 at 16 30 26](https://user-images.githubusercontent.com/4663708/148962870-21e0c16a-5500-49d9-b552-9c2b1779dcae.png)

**Comment by Alena-Shorenko** [comment]
https://www.figma.com/file/ifhZLG9EP01RFmj4UnWtLv/Astro---MP-v.2?node-id=7637%3A46066

Добавила иконку (юзер в процессе голосования)
