### ISSUE TITLE
[Proposals] Proposals can be signed with account different from currently logged into AstroDAO app

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#412]
Steps to reproduce:
1. Add several near wallets to your browser.
2. Open Astro DAO app and sign in with wallet №1. 
3. Open tab with wallet №2 and leave it opened.
4. Click on tab with AstroDAO.
5. Navigate to any of your DAO.
6. Click on "Create Proposal" button.
7. Fill all necessary field and then click on "Propose" button.
8. Wait until user is redirected to wallet to confirm the proposal.

AR: Wrong wallet is used to sign the action. Wallet №2 is used for confirmation while user is logged in with wallet №1.
ER: Transaction confirmations should be only with the wallet which is used in AstroDAO app.

https://user-images.githubusercontent.com/4663708/149150991-e73313f2-0e0e-46c3-a880-8548a2816c3a.mov

**Comment by Izek** [comment]
NOTE: While these wallets belong to same person, transaction for proposal creation is created successfully, but signed with the different from expected wallet.

**Comment by dmytro-almighty** [comment]
we have no control over this behavior
