### ISSUE TITLE
UI / Layout / CSS rendering at incorrect width on page load 

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#422]

**Comment by starpause** [comment]
Difficult to reproduce (happens to me once in a while) and modifying the browser width or opening dev tools makes the page render correctly (must trigger the breakpoint listener)

![image](https://user-images.githubusercontent.com/408953/149363917-929013f1-1ec1-4664-939e-15dcac5831da.png)

**Comment by RomaSha2010** [comment]
Not actual anymore
