### ISSUE TITLE
[Bounty] Bounty statuses are dispayed incorrecty in bounty card

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#424]
![Screenshot 2022-01-13 at 19 53 26](https://user-images.githubusercontent.com/4663708/149383657-a45aec3c-2e46-4ec6-8dab-520e5a2c58e5.png)
![Screenshot 2022-01-13 at 20 00 10](https://user-images.githubusercontent.com/4663708/149384652-3cdbd34d-8cbb-46cc-a3fa-b05d8fd64a37.png)

**Comment by RomaSha2010** [comment]
Not actual anymore
