### ISSUE TITLE
Single DAO is not aligned on the left side

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#440]
**ER:** Single DAO is aligned on the left side

**AR:** Single DAO is in the middle of the Page

![image](https://user-images.githubusercontent.com/94607182/149739704-6b5348cc-6ced-4e7e-8b24-bc1c8f899812.png)

**Comment by Izek** [comment]
AR: Single DAO alignment turns on only after 1024 px width.
ER: Single DAO alignment should turn on only after switching from mobile view to web view.
Reopening
https://user-images.githubusercontent.com/4663708/150818211-96a1fca8-9d49-4a9c-beb0-d4037e43afb0.mov

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed

**Comment by RomaSha2010** [comment]
Verified on testnet. Fixed
