### ISSUE TITLE
DAO settings filters are flickering after switch

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#441]
**STR:**
Open DAO Settings page
Switch between items

**ER:**
Settings items are not flickering after switch

**AR:**
DAO settings filters are flickering after switch

---
https://user-images.githubusercontent.com/94607182/149740698-7392508d-3e40-4bf9-84e3-2876df85b21d.mp4

**Comment by unholywhite** [comment]
Need more details, cause I can't reproduce such flickering. Trying in Chrome and Safari on different platforms.
In what OS and browser you get such effect?

**Comment by RomaSha2010** [comment]
Not actual anymore
