### ISSUE TITLE
Links/icons next to DAO name on the DAO bar

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#463]
Add a "copy DAO wallet" icon and "explorer link" icon next to the DAO name. 

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/408953/150621580-72362551-fdef-4840-ac8a-3deec0dc2d6e.png">

**Comment by RomaSha2010** [comment]
Verified on dev. Implemented

**Comment by RomaSha2010** [comment]
Verified on testnet. Implemented
