### ISSUE TITLE
[Search] Empty search results are displayed if click on (X) button in the Search field

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#467]
AR: Empty search results are displayed.
ER: Previous screen should be displayed. User should be redirected back to screen from which search was called.

https://user-images.githubusercontent.com/4663708/150785040-be5f7c50-02c3-43fb-80af-7403345e1285.mov

**Comment by starpause** [comment]
Hitting "Enter" while search results are loading or after search results are displayed causes a blank page of searches. 

Reopening as it seems related to search state & a blank results page.

https://user-images.githubusercontent.com/408953/156038847-13601c65-2e5b-4882-bdfa-e50bcf95f747.mp4
