### ISSUE TITLE
voting policy not changing

### ISSUE THREAD

**Issue by sainthiago** [near-daos/astro-ui#5]
hello,

we approved a proposal to change the voting policy to 40% but the voting policy of the dao was still 50%.

tx: https://explorer.mainnet.near.org/transactions/8GQFYgsQ1nHXLzsofmThx2E7sk12S988AkCLHt9mDbBf

if you need any extra info let me know.

![Screenshot_20211110-115635_Chrome.jpg](https://user-images.githubusercontent.com/11164548/141109281-739a8650-6b47-4b04-abb1-af99c13de341.jpg)

![Screenshot_20211110-115652_Chrome.jpg](https://user-images.githubusercontent.com/11164548/141109305-4d7713a0-aabf-47f7-b18c-53ba01cbd317.jpg)

thank you

**Comment by VERZUOL1** [comment]
Hi,
If we create a ChangePolicy or Change DAO config policy proposals the proposed changes in will affect the other proposals. Further updates might get rewritten if the current proposal won't get resolved before. In other words, it is possible to override proposed voting policy changes with other proposal once it approved.
Could you please try to create another proposal to change voting policy and approve it? 

Thanks,
Oleg
