### ISSUE TITLE
Bounty Claim button is missed after first claim

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#504]
**To Reproduce**
1. Create Bounty proposal
2. Vote approve
3. Claim bounty

**Expected behavior**
Claim button should be present until all claims are filled

**Screenshots**
![image](https://user-images.githubusercontent.com/94607182/151517458-763e7866-0dd8-4f54-8db5-891e9330e1fb.png)

**Comment by dmytro-almighty** [comment]
its by design, user cannot claim more than 1 bounty in time
