### ISSUE TITLE
[Proposal] "Unknown App" is displayed when user confirms the transaction in the NEAR wallet app

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#518]
**Expected behavior**
"Unknown App" is displayed.

**Expected behavior**
"Astro DAO App" should be displayed.

**Screenshots**
![Screenshot 2022-01-28 at 14 13 38](https://user-images.githubusercontent.com/4663708/151547893-2efd851f-377e-4190-bd3a-59a6cc19f811.png)

**Comment by VERZUOL1** [comment]
Not reproducible anymore.
