### ISSUE TITLE
Layout issue for DAO settings

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#526]
**Describe the bug**
DAO Config and DAO Policy are stacked in a way that makes it difficult if not impossible to navigate to the different sections. 

**To Reproduce**
1. Visit https://app.astrodao.com/dao/curators.sputnik-dao.near/governance/settings
2. Reduce width of browser window until layout bug appears.

**Expected behavior**

Either this layout:
![image](https://user-images.githubusercontent.com/408953/151710578-6742dd98-8b40-4422-912e-3eaf43df0321.png)

Or this layout:
![image](https://user-images.githubusercontent.com/408953/151710593-064bc858-d836-476a-94e5-c1afd0f8fe41.png)

**Screenshots**
<img width="914" alt="image" src="https://user-images.githubusercontent.com/408953/151710297-daf7f519-53c7-4b54-92c9-ab2e00aabebc.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 97.0.4692.99 (Official Build) (64-bit)

**Additional context**

**Comment by RomaSha2010** [comment]
Fixed
