### ISSUE TITLE
[Type Filter] Disable a blue line focus state on the "type of proposal" filter for Safari browser.

### ISSUE THREAD

**Issue by IlliaMiM** [near-daos/astro-ui#53]
STR:
-Open feed
-choose a filter (ex. Financial)

Expected result:
no blue lines at top and bottom 

Actual result:
Blue lines

<img width="560" alt="Screenshot 2021-11-25 at 15 02 25" src="https://user-images.githubusercontent.com/95025746/143452965-ba85820c-1a24-458b-8706-355fdf08c825.png">

**Comment by VERZUOL1** [comment]
Fixed in latest version
