### ISSUE TITLE
User with 2FA unable to vote for Functional Call proposal

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#560]
**Describe the bug**
Error: {"index":0,"kind":{"ExecutionError":"Exceeded the prepaid gas."}}
Minimum TGas value of 100 does not lead to a successful result

**To Reproduce**
1. Create a functional call proposal and set TGas value to 100
2. Vote Approve

**Expected behavior**
FC proposal executed successfully after vote

**Screenshots**

---
![image](https://user-images.githubusercontent.com/94607182/151844777-fca7635c-01fc-4583-808e-257017d4a8f5.png)

**Comment by dmytro-almighty** [comment]
cannot be fixed on Astro UI side
