### ISSUE TITLE
Transactions for user with 2FA are wrapped in the Functional Call proposal and overrides the attached GAS

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#567]
**Describe the bug**
Simple 'add_proposals' transactions created from 2 transactions. The first transaction is wrapped in Functional Call. The attached GAS is overridden. And the second transaction is add_proposal.
[First transaction](https://explorer.testnet.near.org/transactions/7B5CyfKic9m7bDWM5u2LAqtohEKgSAPQGLL4uefdyC7y)
[Second transaction](https://explorer.testnet.near.org/transactions/2JhLGoiJF7Jkz7Pp4TD74ejM2wPxrNtL5HcBdo2VDRjT)

**To Reproduce**
1. Create Poll Proposal by user with 2FA and attach 50Gas

**Expected behavior**
Attached GAS is not overwritten

**Comment by dmytro-almighty** [comment]
cannot be fixed on Astro UI side
