### ISSUE TITLE
[DAO Settings] Image and logo is not updated immediately after approving corresponding proposal

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#57]
Steps:
1. Go to DAO
2. Create proposal to change cover and logo
3. Navigate to proposal detailed screen
4. Approve the proposal

AR: Cover and logo changed, however they're not updated across the app immediately.
ER: After approving proposal UI should be updated with new cover and logo across the app
![Screenshot 2021-11-25 at 19 04 01](https://user-images.githubusercontent.com/4663708/143480447-05865ec4-a69a-4ade-9ff0-0dfc7619b29d.png)
![Screenshot 2021-11-25 at 18 57 35](https://user-images.githubusercontent.com/4663708/143480452-cccedc94-4370-44dd-bdcb-01faeb60c8fe.png)

NOTE: It might appear that this is a common issue of AstrDAO UI: After confirmation of any action in NEAR wallet, when user redirected back to the app UI is not updated.

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed
