### ISSUE TITLE
[Bounties] Zero values are dipslayed for FT inside of Bounty cards in Bounties page

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#59]
Steps:
1. Navigate to https://testnet.app.astrodao.com/dao/dadada2.sputnikv2.testnet/tasks/bounties

AR: 0 FTs are displayed.
ER: Actual amount of FT should be displayed in each bounty card for FT
![Screenshot 2021-11-25 at 20 13 20](https://user-images.githubusercontent.com/4663708/143487103-9960eaf9-8907-4f59-88ea-354222cc2f99.png)

**Comment by dmytro-almighty** [comment]
fixed in dev

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed
