### ISSUE TITLE
UI/UX iteration 

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#6]
I had written these up in a Google Doc before we switched to Github, pasting here:

https://docs.google.com/document/d/1arEwOi7qvE8EFvBfiv02P7_9hNOuXOCZfM7L01wmtGc/edit?usp=sharing

In the future I'll file issue in Github directly. Thanks!

**Comment by VERZUOL1** [comment]
Fixed.
Should be available on testnet this evening.

**Comment by starpause** [comment]
![image](https://user-images.githubusercontent.com/408953/141886522-ff8608f4-5335-45df-b0e7-e6eeb3bc10c2.png)

When not logged in a user should see the "Global Feed" and "All Communities". Currently it shows "My Communities" and "All Communities"

**Comment by starpause** [comment]
![image](https://user-images.githubusercontent.com/408953/141886795-1128ded8-073e-4919-b5f6-f3c3501802ff.png)

Default landing page for a logged out user is the "Global Feed" page. Currently it's the "All Communities" page.

**Comment by VERZUOL1** [comment]
Fixed. Merged to main branch.
