### ISSUE TITLE
[Notifications] DAO's flag is not displayed in Notification card

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#680]
**Expected behavior**
DAO's flag should be displayed in the notification card

**Screenshots**
![Screenshot 2022-02-16 at 18 56 41](https://user-images.githubusercontent.com/4663708/154319965-b06f4d79-0486-417a-9551-c1f4d9b88e24.png)

**Comment by VERZUOL1** [comment]
Fixed in latest build
