### ISSUE TITLE
[My DAOs] List of my DAOs is not displayed in Ms Edge on Mac

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#683]
**Describe the bug**
List of My DAOs is not displayed.
Locales are not displayed.

**To Reproduce**

1. Go to App.
2. Connect your account to AstrDAOapp
3. Click on "My DAOs" link

**Expected behavior**
List of My DAOs should be displayed.
Locales should be displayed.

**Screenshots**

https://user-images.githubusercontent.com/4663708/154523080-877bcc15-e23e-4e7e-8b0e-4d1c2aa6d6aa.mov

**Desktop (please complete the following information):**

- OS: MacOS
- Browser Ms Edge
- Version Version 98.0.1108.55 (Official build) (x86_64)

**Comment by VERZUOL1** [comment]
Not reproducible on latest build
