### ISSUE TITLE
[Bounty] It's impossible to finalize Bounty Done proposal after proposal gets expired

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#686]
**Describe the bug**
If proposal "Bounty Done" is expired it is impossible to finalize it. Transaction approval fails with 

`"ExecutionError":"Smart contract panicked: panicked at 'ERR_NO_BOUNTY_CLAIM'`

https://dev.app.astrodao.com/dao/dadada4.sputnikv2.testnet/proposals/dadada4.sputnikv2.testnet-24
https://explorer.testnet.near.org/transactions/EHbMq4Bc56FsZAWLwL5udrK1WCpKH1SfxSX6EuZZJjjF

**To Reproduce**

There should be DAO with at least 3 members and voting threshold should need at least two votes.

1. Claim a bounty.
2. Complete bounty
3. Vote on approve with 1st user
4. Vote on reject with 2nd user
5. Wait until proposal gets expired
6. Try to finalize proposal

**Expected behavior**
Proposal should be finalized. 

**Screenshots**
https://user-images.githubusercontent.com/4663708/154547312-993478e8-d808-4305-ba75-ea4c82851c64.mov

**Comment by dmytro-almighty** [comment]
cannot be fixed on Astro UI side
