### ISSUE TITLE
Removed Bounty Done proposal doesn't remove Bounty claim

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#710]
**Describe the bug**
Removing proposal on a smart contract will remove a claim

**To Reproduce**

1. Create Bounty
2. Vote approve
3. Create a Claim
4. Click Complete button and create BountyDone proposal
5. Remove BountyDone proposal

**Expected behavior**
Claim removed

**Actual result:**
Removed Bounty Done proposal doesn't remove Bounty claim

---
**Screenshots**
![image](https://user-images.githubusercontent.com/94607182/155140391-622a754a-5ddf-42d3-a4ff-519b68384efc.png)

**Comment by dmytro-almighty** [comment]
issue with smartcontract logic, cant be fixed on Astro UI
