### ISSUE TITLE
[MOBILE] Error message doesn't appear after pressing Confirm button on "Confirm your claim" popup

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#719]
**Describe the bug**
An issue applicable for the "Confirm your claim" popup on Bounty page

**To Reproduce**

1. Create Bounty
2. Click Claim button on Bounty
3. SetTGas value to 5
4. Click Confirm button

**Expected behavior**
Error message appears pressing on Confirm button

**AR:**
Error message doesn't appear after pressing Confirm button on "Confirm your claim" popup

---
**Screenshots**
![image](https://user-images.githubusercontent.com/94607182/155351716-c5e28921-33d3-4c7f-9969-1f1d51923a03.png)

**Smartphone (please complete the following information):**
- Device: Pixel 5
- OS: Android 12
- Browser Chrome
- Version 98

**Comment by VERZUOL1** [comment]
This is a behavior we expect. No plans to implement.
