### ISSUE TITLE
After creating new DAOs it takes at least minutes to show up in UI

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#741]
After creating new DAOs it takes at least minutes to show up in UI

**Comment by chluff** [comment]
I created a DAO 3 days ago and it still doesn't show up. But I didn't create from the Astro UI so I don't know if it matters here.
[multicall.sputnik-dao.near](https://explorer.near.org/accounts/multicall.sputnik-dao.near)

**Comment by dmytro-almighty** [comment]
cant reproduce, sometime it might happens because of the indexer delays - cant be fixed on Astro side
