### ISSUE TITLE
Page Unresponsive error in Chrome

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#763]
**Describe the bug**
![image](https://user-images.githubusercontent.com/408953/157491886-314e332f-53b9-4915-b99e-7ae02c8137ed.png)

**To Reproduce**
This message comes up when I'm using Astro on a gaming/3d rendering pc desktop. This message happens more frequently when I'm using Astro on an old macbook.

**Additional context**
Trevor's thoughts on possible cause: _Id guess its too many RPC calls checking basic status - those can stack up and crash tabs the way that the websocket is getting used_

**Comment by dmytro-almighty** [comment]
cant reproduce, will keep it open for more detailed steps to reproduce
