### ISSUE TITLE
[UI][CREATE PROPOSAL] Available groups are doubled at "Group" dropdown

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#84]
**STR:**
- Open DAO
- Click on the "Create Proposal" button
- Select proposal type "Propose to Add Member to Group"
- Click on the "Group" dropdown

**Expected result:**
- Available groups without duplication are present

**Actual result:**
- Available groups with duplication are present

![image](https://user-images.githubusercontent.com/94607182/143916198-7edb79d5-c697-49d2-9072-31ee8273c252.png)

**Comment by VERZUOL1** [comment]
Fixed in latest build

**Comment by RomaSha2010** [comment]
Verified on dev. Fixed
