### ISSUE TITLE
The .near wallet do not connect

### ISSUE THREAD

**Issue by crypto-musica-lab** [near-daos/astro-ui#886]
**Describe the bug**
Once I try to connect the wallet .near its connect for a millisecond and then goes down

**To Reproduce**

1. press the Near buttom
2. Click on connect wallet
3. symbol of connecting
4. connected by a millisecond
5. goes down

**Expected behavior**
I wantes to connect and create a proposal in the green plus buttom

**Screenshots**

**Desktop (please complete the following information):**

- OS: [iOS]
- Browser [Brave

**Smartphone (please complete the following information):**

- Version [big sur]

**Additional context**

**Comment by dmytro-almighty** [comment]
@ArnoldTravieso can you please try to clear cookies and localstorage for the appastro.dao page and try to perform login flow again?

**Comment by dmytro-almighty** [comment]
was fixed by cleaning the cookies
