### ISSUE TITLE
Land user back on the page they were on after voting for a proposal

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#893]
**Is your feature request related to a problem? Please describe.**
Currently if a user is on the [proposals page](https://app.astrodao.com/dao/daocubator.sputnik-dao.near/proposals) and votes on a proposal, after the TX, AstroDAO will land the user on the [page of the proposal they just voted on](https://app.astrodao.com/dao/daocubator.sputnik-dao.near/proposals/daocubator.sputnik-dao.near-75), rather than on the [proposals page](https://app.astrodao.com/dao/daocubator.sputnik-dao.near/proposals) where they previously were. This is confusing and makes it a pain to vote on multiple proposals at a time (such as approving weekly payouts). 

**Describe the solution you'd like**
If a user is on the list of proposals page and they vote, land them back on that list of proposals page.

**Comment by VERZUOL1** [comment]
Implemented
