### ISSUE TITLE
hitting "enter" or "return" after typing a search term shows 0 results (even if there are matches) 

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#895]
**Additional context**
I was searching for "daocubator" which was showing search results when I typed that word in the search bar. Then I hit "enter" and no results are shown.

<img width="1018" alt="Screen Shot 2022-04-10 at 7 34 35 PM" src="https://user-images.githubusercontent.com/408953/162655610-6ce6994c-a7af-4137-b1f2-e2f7a27b20c8.png">

**Comment by RAnis2017** [comment]
Hi, I have some time today and I'd like to fix this issue. Waiting for the assignment and I'll start. :)
