### ISSUE TITLE
issue wallet payouts from astro dao 

### ISSUE THREAD

**Issue by carolinecares9** [near-daos/astro-ui#896]
krisullis members unable to connect near wallet onto astro dao by themselves

several members are not able to connect their wallets 
also members cannot raise their payouts on their own

we have to raise payouts for them and then make transfers

![WhatsApp Image 2022-04-11 at 9 53 19 AM](https://user-images.githubusercontent.com/90549621/162669240-1f0cbbd3-fdc1-4d15-b40e-7a6a658f84b0.jpeg)

here is one examples of the issue from one of our members 

appreciate your support in the following:
1. helping our members connect near wallets to astro dao
2. that each member can raise their own payouts

**Comment by dmytro-almighty** [comment]
hey @carolinecares9,  can you please try to clear cookies and localstorage for the appastro.dao page and try to perform login flow again?

**Comment by VERZUOL1** [comment]
@carolinecares9 Hi! Could you please verify if no popups are blocked in browser? It is quite common issue
<img width="479" alt="image" src="https://user-images.githubusercontent.com/40799684/162758895-a9086927-c3e9-48f7-b933-2a38d1713418.png">
Popup should be allowed from this page so user can connect to his wallet.

**Comment by dmytro-almighty** [comment]
Issue related to blocked popup

**Comment by carolinecares9** [comment]
Thank you we fixed this issue 😊

Caroline Cares
