### ISSUE TITLE
Unable to connect to near wallet and cannot vote on AStro DAO

### ISSUE THREAD

**Issue by sahanamanoj** [near-daos/astro-ui#897]
**Describe the bug**
I am unable to connect to Near wallet  sahanamanoj.near and vote on proposals

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to h
![wallet pic](https://user-images.githubusercontent.com/103413797/162696540-fe019344-37db-4585-aa80-2040c53d4492.jpeg)
elp explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dmytro-almighty** [comment]
@sahanamanoj  can you please try to clear cookies and localstorage for the appastro.dao page and try to perform login flow again?

**Comment by VERZUOL1** [comment]
@sahanamanoj Hi! From your screenshot I see that popup is blocked. 
<img width="479" alt="image" src="https://user-images.githubusercontent.com/40799684/162758480-b2e1d1b9-e279-4837-9ede-907fd833cb01.png">
You should allow popups fro this page so you can login into your NEAR account in wallet.

**Comment by sahanamanoj** [comment]
i have unblocked the popup yet the same message
[image: image.png]

**Comment by sahanamanoj** [comment]
Hi
 Its fine now my near wallet is getting connected to astro dao, so am i
able to vote now on the proposals?

kindly reply

**Comment by sahanamanoj** [comment]
I tried voting on the below proposal however i was unable too.
[image: image.png]
 sahanamanoj.near is my wallet ID
[image: image.png]

**Comment by sahanamanoj** [comment]
i was able to connect to astro dao  and this is the screen at the moment ,
i dont see my near wallet on astro dao

so looks like its not yet resolved

[image: image.png]

**Comment by sahanamanoj** [comment]
hello ,

Thanks i was able to connect and vote too( cleared the cookies as advised )

**Comment by Wabinab** [comment]
I also have same problem. Actually, after I connected on the Astro DAO, it immediately logs me out (I see myself logged-in, then the browser forced refresh itself, then I got logged out again). It seems like there's some issue with the site; I try logging in with another wallet on incognito, there seems to be no problem. No cookie/cache clearing helps.

**Comment by GaloisField2718** [comment]
I think I have a related problem : I had created a proposal "Add a new group" and when I vote it's opened a contract approval but I have : {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'ERR_UNSUPPORTED_ROLE', src/policy.rs:369:30"}}. And so, it's impossible for me to reject proposal. 
What can I do ? 
resurg.sputnikv2.testnet

**Comment by dmytro-almighty** [comment]
@GaloisField2718  your issues is not related to the wallet,  I assume you have something with DAO config
