### ISSUE TITLE
Implement DAO upgrade wizard

### ISSUE THREAD

**Issue by dmytro-almighty** [near-daos/astro-ui#901]

**Comment by dmytro-almighty** [comment]
https://www.figma.com/file/K5s2NnxIYn3kPXzionbGWq/Astro---MP-v.-3?node-id=11920%3A84745

**Comment by starpause** [comment]
Contract integration guide via Trevor (to support this UI):
https://github.com/near-daos/sputnik-dao-contract/wiki/Client-DAO-Upgrade-Integration-Guide

**Comment by starpause** [comment]
What Launch Darkly flags are relevant to accommodating DAOs on v2 (pre upgrade) and v3 (post upgrade) contracts?
