### ISSUE TITLE
Add indicator that a vote caused the proposal to be approved.

### ISSUE THREAD

**Issue by starpause** [near-daos/astro-ui#912]
**Is your feature request related to a problem? Please describe.**
It's difficult to find which vote caused a proposal to be approved. Can we add an icon or indicator that a vote caused the proposal to be executed?

<img width="695" alt="image" src="https://user-images.githubusercontent.com/408953/163069099-9f6b76f2-f6bf-4d66-ab12-f9bda369593b.png">

**Comment by VERZUOL1** [comment]
Just thinking - I suppose this should be the last vote in proposal and we know its timestamp so I think we can handle this

**Comment by VERZUOL1** [comment]
Implemented
