### ISSUE TITLE
building an extract button to extract all transaction detail into excel (using period as a filter)

### ISSUE THREAD

**Issue by souricky** [near-daos/astro-ui#93]
Hi,

Is there anyway we could build a button where it extracts all the transactions within a set period to excel format?

**Comment by starpause** [comment]
Interesting request. While this could eventually be built into the Astro interface, I think that it could be achieved more directly and quickly through GraphQL against a DAO contract like [https://explorer.mainnet.near.org/accounts/news.sputnik-dao.near](https://explorer.mainnet.near.org/accounts/news.sputnik-dao.near). Here's a getting started guide for [Building Subgraphs on NEAR](https://thegraph.com/docs/supported-networks/near).
