### ISSUE TITLE
Mint governance token

### ISSUE THREAD

**Issue by dmytro-almighty** [near-daos/astro-ui#944]
* implement custom functional call UI  
* integrate with token factory
* implement existing token flow

https://www.figma.com/file/K5s2NnxIYn3kPXzionbGWq/Astro---MP-v.-3?node-id=8713%3A55557

**Comment by karpovdmitryod** [comment]
https://www.figma.com/file/K5s2NnxIYn3kPXzionbGWq/Astro---MP-v.-3?node-id=8713%3A55557
