### ISSUE TITLE
DAO name and flag is not clickable (even though the hand cursor shows up)

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#95]
Issue 1 https://github.com/near-daos/astro-ui/issues/91
![image](https://user-images.githubusercontent.com/94607182/144017278-25994b61-f190-46c2-aeec-fedc9416dd5d.png)

**Comment by dmytro-almighty** [comment]
cannot reproduce it

**Comment by VERZUOL1** [comment]
Do you have any details about browser, OS? Currently we cannot reproduce it on any device/browser

**Comment by dmytro-almighty** [comment]
cannot reproduce
