### ISSUE TITLE
[DAO Settings] Add possibility to set permissions and add users during group creation

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#952]
When user creates a proposal for new group creation, please add following:

Possibility to set the permissions for a group
Permissions should be disabled by default
User should be able to add multiple wallets in this proposal

After proposal approval there should be created a group with the settings set in the proposal

![Screenshot 2022-04-18 at 20 15 45](https://user-images.githubusercontent.com/4663708/163846025-f3cd038c-1efa-42c7-8927-4f5a6ccaa246.png)
![Screenshot 2022-04-18 at 18 30 55](https://user-images.githubusercontent.com/4663708/163846029-9e7acaa7-3eda-4c4f-9a25-ade04decaba2.png)
![Screenshot 2022-04-18 at 18 30 34](https://user-images.githubusercontent.com/4663708/163846035-4538dc28-766d-4f8a-8433-971cb46f018f.png)

**Comment by GaloisField2718** [comment]
I had purpose to add a new group (without asking what is the role of the new group), and now the DAO is unusable. {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'ERR_UNSUPPORTED_ROLE', src/policy.rs:369:30"}}
resurg.sputnikv2.testnet
