### ISSUE TITLE
I had purpose to add a new group (without asking what is the role of the new group), and now the DAO is unusable. {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'ERR_UNSUPPORTED_ROLE', src/policy.rs:369:30"}} when I try to vote

### ISSUE THREAD

**Issue by GaloisField2718** [near-daos/astro-ui#957]
I had purpose to add a new group (without asking what is the role of the new group), and now the DAO is unusable. {"index":0,"kind":{"ExecutionError":"Smart contract panicked: panicked at 'ERR_UNSUPPORTED_ROLE', src/policy.rs:369:30"}}
resurg.sputnikv2.testnet

_Originally posted by @GaloisField2718 in https://github.com/near-daos/astro-ui/issues/952#issuecomment-1102676442_

**Comment by GaloisField2718** [comment]
Sorry for the name of the issue I can modify to be more readable and understandable.

**Comment by GaloisField2718** [comment]
I think it's better in sputnik-dao-contracts sorry for bad placing

**Comment by dmytro-almighty** [comment]
@GaloisField2718 thanks for reporting, we able to reproduce it anyway from the UI side, but we didn't find a root cause yet
