### ISSUE TITLE
Move elements

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#99]
Issue 5 https://github.com/near-daos/astro-ui/issues/91

- Move Status ( “All | Active | Approved | Failed” ) to the tabs which are always visible
- Make “Active” the default. If there are no Active proposals display “All”
- Make the display the same across “Global Feed” and “My Feed”
- Always have Type (“All | Governance | Financial | Bounties | Members | Polls”) hidden in the select/dropdown, on both the My Feeds page and Global Feeds page. 
- Use the select/dropdown view at all screen sizes and breakpoints (desktop/tablet/mobile)

![image](https://user-images.githubusercontent.com/94607182/144019352-65397b0c-0086-46e4-a771-ecddc5b0efe2.png)
![image](https://user-images.githubusercontent.com/94607182/144019647-a43d50ce-e997-4fab-8ad4-0b5f03fb506a.png)

**Comment by dmytro-almighty** [comment]
Making default filter is active - make sense. But reorganizing the filters and hiding the type of the proposal will leave people more confused. The proposal type has higher priority over proposal status and also works as an educational element. It shows to the user what kind of proposals can exist in the system.  Also, the status filter collapses to the Icon when there is not enough space to be rendered.
