### ISSUE TITLE
[All DAOs] Default flag is not displayed in the list of DAOs

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#995]
**Describe the bug**

**Expected behavior**
Default flag should be displayed

**Screenshots**
![Screenshot 2022-04-25 at 14 50 22](https://user-images.githubusercontent.com/4663708/165083763-208c4d9f-a400-440c-aac8-0d0726cbe200.png)

**Comment by dmytro-almighty** [comment]
fixed in 3.0.6
