### ISSUE TITLE
[Notifications Hub] Nothing happens if user clicks on "Mark as read" or "Archive" buttons in Safari

### ISSUE THREAD

**Issue by Izek** [near-daos/astro-ui#997]
**Describe the bug**
When user navigates to Notifications Hub and tries to interact with the notifications then nothing happens. No any reuests are sent, there is not reaction on user actions like Mark as Read / All or Archive / All.

**Expected behavior**
All buttons in Notifications Hub should be functional

**Screenshots**

https://user-images.githubusercontent.com/4663708/165108809-3e035149-f771-40c0-b1d9-f6f8b53d4f1e.mov

**Comment by VERZUOL1** [comment]
Already fixed
